// Los mundos imaginados, definidos como DATOS. Nada de esto se le muestra al
// LLM tal cual: la mascota "vive" el texto de las reacciones y su cerebro
// extrae conceptos ("hongo rojo → dolor de panza", "semáforo en rojo → carro").
//
// Cómo leer una reacción: `p` es la probabilidad OCULTA de que el verbo salga
// bien; okText/failText es lo que percibe; okReward/failReward mueven la
// política; `effects` son deltas sobre los impulsos (energy, boredom,
// loneliness), se apliquen o no las cosas bien. Hay objetos peligrosos (p ≤ 0.2,
// fallo −0.6/−0.8 y energía −0.3) y objetos seguros (p ≥ 0.9) para que la
// cautela tenga de dónde aprender. `hiddenAfter` esconde objetos hasta que la
// zona se ha visitado N veces: hay cosas que solo se descubren volviendo.
import type { ImaginedEnvSpec } from "./imagined";

// --- 🌲 el bosque ---

const BOSQUE: ImaginedEnvSpec = {
  id: "bosque",
  name: "El bosque",
  emoji: "🌲",
  intro: "Un bosque de niebla con un claro, un arroyo y una espesura que asusta.",
  verbs: [
    { id: "oler", label: "oler", riskHint: 0.05, costEnergy: 0.03 },
    { id: "tocar", label: "tocar", riskHint: 0.3, costEnergy: 0.05 },
    { id: "comer", label: "comer", riskHint: 0.6, costEnergy: 0.08 },
    { id: "trepar", label: "trepar", riskHint: 0.5, costEnergy: 0.15 },
    { id: "jugar", label: "jugar con", riskHint: 0.2, costEnergy: 0.1, ludic: true },
    { id: "esconderse", label: "esconderse en", riskHint: 0.1, costEnergy: 0.05, ludic: true },
  ],
  ambient: {
    day: [
      "Entra un sol tibio entre las ramas y el aire huele a tierra mojada.",
      "Es de día: se oyen pajaritos y una brisa mueve las hojas altas.",
      "La niebla de la mañana se está levantando y todo gotea despacio.",
    ],
    night: [
      "Es de noche: el bosque suena a grillos y a ramas que crujen sin viento.",
      "Bajo la luna aparecen luciérnagas verdes flotando entre los helechos.",
      "Hace frío y está oscuro; solo se ve lo que la luna alcanza a tocar.",
    ],
  },
  zones: [
    {
      id: "claro",
      name: "el claro",
      desc: "Un claro redondo de pasto corto rodeado de árboles viejos, con un tronco caído en el medio.",
      danger: 0.1,
      links: ["arroyo", "espesura"],
      objects: [
        {
          id: "flor-amarilla",
          label: "flor amarilla",
          kind: "cosa",
          desc: "Una flor amarilla grande, con el centro lleno de polen y una abeja dando vueltas.",
          reactions: {
            oler: {
              p: 0.9,
              okText: "Huele a miel tibia y a algo dulce que te da ganas de quedarte.",
              failText: "Metiste la nariz muy adentro y el polen te hizo estornudar tres veces.",
              okReward: 0.3,
              failReward: -0.1,
            },
            tocar: {
              p: 0.7,
              okText: "Los pétalos son suaves y se cierran un poquito cuando los rozas.",
              failText: "La abeja no quería visitas y te dio un aletazo en la cara.",
              okReward: 0.2,
              failReward: -0.2,
            },
            comer: {
              p: 0.5,
              okText: "Los pétalos saben a lechuga con azúcar. Raro, pero rico.",
              failText: "Te comiste el polen con todo y te quedó la lengua amarga y pegajosa.",
              okReward: 0.2,
              failReward: -0.3,
            },
            jugar: {
              p: 0.8,
              okText: "Sacudiste la flor y llovió polen dorado sobre tu cabeza. Te reíste.",
              failText: "Le diste tan fuerte que se le cayeron todos los pétalos. Se ve triste.",
              okReward: 0.3,
              failReward: -0.2,
              effects: { boredom: -0.2 },
            },
          },
        },
        {
          id: "tronco-caido",
          label: "tronco caído",
          kind: "cosa",
          desc: "Un tronco caído, hueco por dentro, cubierto de musgo blando y con hormigas caminando en fila.",
          reactions: {
            oler: {
              p: 0.95,
              okText: "Huele a madera húmeda y a hongos viejos. Un olor de cosa que lleva años ahí.",
              failText: "Una hormiga se te metió en la nariz. Fue horrible por un segundo.",
              okReward: 0.2,
              failReward: -0.1,
            },
            trepar: {
              p: 0.75,
              okText: "Subiste de un salto. Desde arriba se ve todo el claro y el camino al arroyo.",
              failText: "El musgo resbala: te fuiste de bruces al pasto.",
              okReward: 0.35,
              failReward: -0.3,
            },
            esconderse: {
              p: 0.9,
              okText: "Te metiste en el hueco: oscuro, seco y calientito. Nadie te puede ver aquí.",
              failText: "El hueco estaba ocupado por un sapo gordo que no se quiso mover.",
              okReward: 0.3,
              failReward: -0.1,
              effects: { energy: 0.1 },
            },
            jugar: {
              p: 0.6,
              okText: "Corriste por encima del tronco de punta a punta como una equilibrista.",
              failText: "Pisaste la fila de hormigas y se te subieron a las patas, picando.",
              okReward: 0.3,
              failReward: -0.3,
            },
          },
        },
        {
          id: "mariposa-azul",
          label: "mariposa azul",
          kind: "cosa",
          desc: "Una mariposa azul brillante que se posa un segundo en cada cosa y nunca se queda quieta.",
          reactions: {
            tocar: {
              p: 0.25,
              okText: "Se posó en tu nariz un segundo. Las alas hacían cosquillas.",
              failText: "Apenas te acercaste se fue volando alto, lejos de tu alcance.",
              okReward: 0.5,
              failReward: -0.1,
            },
            jugar: {
              p: 0.5,
              okText: "La perseguiste en círculos por el claro hasta marearte de risa.",
              failText: "Corriste tras ella sin mirar y te chocaste con el tronco caído.",
              okReward: 0.4,
              failReward: -0.3,
              effects: { boredom: -0.3 },
            },
            comer: {
              p: 0.1,
              okText: "La atrapaste con la boca, te dio pena y la soltaste. Sabía a polvo.",
              failText: "Saltaste con la boca abierta y solo mordiste aire. La mariposa se rió (parecía).",
              okReward: 0.05,
              failReward: -0.2,
            },
          },
        },
        {
          id: "piedra-tibia",
          label: "piedra tibia",
          kind: "cosa",
          desc: "Una piedra plana y gris en el centro del claro, tibia porque le da el sol toda la mañana.",
          reactions: {
            tocar: {
              p: 0.95,
              okText: "Está calientita como una cama recién dejada. Te dan ganas de echarte.",
              failText: "De noche la piedra está helada y te dejó las patas entumecidas.",
              okReward: 0.3,
              failReward: -0.1,
            },
            esconderse: {
              p: 0.3,
              okText: "Te hiciste bolita debajo del borde de la piedra. Cabías justo.",
              failText: "No hay dónde esconderse en una piedra plana. Te quedaste a la vista, ridícula.",
              okReward: 0.2,
              failReward: -0.1,
            },
            oler: {
              p: 0.9,
              okText: "Huele a sol y a polvo caliente. Un olor de siesta.",
              failText: "Un lagarto estaba tomando sol en ella y te sopló en la cara.",
              okReward: 0.15,
              failReward: -0.1,
            },
            jugar: {
              p: 0.7,
              okText: "Te echaste panza arriba sobre la piedra tibia y rodaste hasta caer al pasto. Otra vez.",
              failText: "Rodaste muy fuerte y te golpeaste la cabeza contra el borde.",
              okReward: 0.3,
              failReward: -0.25,
              effects: { energy: 0.1 },
            },
          },
        },
      ],
    },
    {
      id: "arroyo",
      name: "el arroyo",
      desc: "Un arroyo angosto de agua clara y fría que baja saltando entre piedras redondas.",
      danger: 0.2,
      links: ["claro", "espesura"],
      objects: [
        {
          id: "agua-del-arroyo",
          label: "agua del arroyo",
          kind: "cosa",
          desc: "El agua corre transparente y helada; se ven las piedritas del fondo y burbujas que se van.",
          reactions: {
            tocar: {
              p: 0.9,
              okText: "Está fría, fría, fría. Te quedaste con la pata metida hasta que se acostumbró.",
              failText: "La corriente tiró de tu pata y te sentaste en el agua de golpe.",
              okReward: 0.3,
              failReward: -0.2,
            },
            comer: {
              p: 0.85,
              okText: "Bebiste a lengüetazos. El agua sabe a piedra limpia y a frío.",
              failText: "Tragaste agua por la nariz y tosiste un buen rato.",
              okReward: 0.4,
              failReward: -0.2,
              effects: { energy: 0.15 },
            },
            oler: {
              p: 0.95,
              okText: "Huele a nada y a todo: a musgo, a piedra, a lluvia vieja.",
              failText: "Te acercaste tanto que una salpicadura te entró al ojo.",
              okReward: 0.15,
              failReward: -0.05,
            },
            jugar: {
              p: 0.7,
              okText: "Chapoteaste hasta empaparte y dejar el arroyo lleno de ondas.",
              failText: "Resbalaste en una piedra con lama y te llevó la corriente unos metros.",
              okReward: 0.4,
              failReward: -0.35,
              effects: { boredom: -0.3 },
            },
          },
        },
        {
          id: "rana-verde",
          label: "rana verde",
          kind: "persona",
          desc: "Una rana verde y gorda sentada en una piedra, con la garganta inflándose como un globo.",
          reactions: {
            tocar: {
              p: 0.4,
              okText: "Está fría y resbalosa. Parpadeó despacio y no se movió.",
              failText: "Saltó al agua antes de que la tocaras y te salpicó entera.",
              okReward: 0.3,
              failReward: -0.1,
            },
            jugar: {
              p: 0.5,
              okText: "Saltaste cuando ella saltó, y ella saltó cuando tú saltaste. Un juego.",
              failText: "Le saltaste encima y se metió al agua, ofendida. No volvió a salir.",
              okReward: 0.4,
              failReward: -0.2,
              effects: { boredom: -0.2 },
            },
            comer: {
              p: 0.15,
              okText: "La lamiste apenas y sabía tan amargo que la dejaste enseguida. Mala idea.",
              failText: "Su piel suelta un veneno amargo: te dio un dolor de panza horrible y náuseas.",
              okReward: -0.1,
              failReward: -0.6,
              effects: { energy: -0.3 },
            },
            oler: {
              p: 0.9,
              okText: "Huele a barro y a lama. Ella también te olió: infló la garganta y croó.",
              failText: "Croó tan fuerte en tu oreja que saltaste hacia atrás.",
              okReward: 0.2,
              failReward: -0.05,
            },
          },
        },
        {
          id: "piedras-lisas",
          label: "piedras lisas",
          kind: "cosa",
          desc: "Piedras redondas y lisas que asoman en el arroyo como un camino para cruzar.",
          reactions: {
            trepar: {
              p: 0.6,
              okText: "Saltaste de piedra en piedra hasta la otra orilla sin mojarte ni una pata.",
              failText: "La tercera piedra se movió y caíste al agua helada hasta el cuello.",
              okReward: 0.4,
              failReward: -0.4,
            },
            tocar: {
              p: 0.9,
              okText: "Son suaves como huevos. Una tiene una raya blanca que la cruza entera.",
              failText: "La que tocaste tenía lama y se te resbaló la pata al agua.",
              okReward: 0.2,
              failReward: -0.1,
            },
            jugar: {
              p: 0.65,
              okText: "Empujaste una piedrita al agua y sonó plop. Otra: plop. Te encantó.",
              failText: "Quisiste mover una grande y te aplastaste la pata. Ay.",
              okReward: 0.3,
              failReward: -0.3,
            },
          },
        },
        {
          id: "pez-plateado",
          label: "pez plateado",
          kind: "cosa",
          desc: "Un pez pequeño y plateado que se queda quieto contra la corriente y de pronto desaparece.",
          reactions: {
            tocar: {
              p: 0.2,
              okText: "Lo rozaste con la punta de la pata: frío y liso como una moneda mojada.",
              failText: "Metiste la pata y el pez se esfumó. Solo quedó tu reflejo temblando.",
              okReward: 0.5,
              failReward: -0.1,
            },
            comer: {
              p: 0.1,
              okText: "Lo pescaste de un zarpazo. Sabía a arroyo. Te sentiste cazadora.",
              failText: "Te tiraste al agua con todo y lo único que atrapaste fue un resfrío.",
              okReward: 0.6,
              failReward: -0.4,
              effects: { energy: -0.15 },
            },
            oler: {
              p: 0.8,
              okText: "Desde la orilla huele a agua y a algo de pescado, apenas.",
              failText: "Se te fue la cara al agua tratando de olerlo. Nada que oler bajo el agua.",
              okReward: 0.15,
              failReward: -0.1,
            },
          },
        },
      ],
    },
    {
      id: "espesura",
      name: "la espesura",
      desc: "Árboles apretados, poca luz, raíces que sobresalen como trampas y un olor fuerte a hongos.",
      danger: 0.6,
      links: ["claro", "arroyo", "cueva"],
      objects: [
        {
          id: "hongo-rojo",
          label: "hongo rojo",
          kind: "cosa",
          desc: "Un hongo rojo con puntos blancos al pie de un árbol, brillante como si fuera de plástico.",
          reactions: {
            oler: {
              p: 0.9,
              okText: "Huele a tierra y a algo dulzón que no es de fiar.",
              failText: "Soltó una nube de polvo cuando te acercaste y te ardió la nariz.",
              okReward: 0.15,
              failReward: -0.15,
            },
            tocar: {
              p: 0.7,
              okText: "Es blando y frío. Se le quedó marcada tu pata en el sombrero.",
              failText: "Se deshizo en una masa babosa que no se te salía de la pata.",
              okReward: 0.1,
              failReward: -0.2,
            },
            comer: {
              p: 0.15,
              okText: "Mordiste una puntita. Sabía a nada y te dio sueño. Tuviste suerte.",
              failText: "El hongo rojo te dio un dolor de panza terrible: te retorciste un buen rato en el suelo.",
              okReward: 0.1,
              failReward: -0.8,
              effects: { energy: -0.3 },
            },
            jugar: {
              p: 0.5,
              okText: "Le diste un golpecito y salió una nubecita de esporas que flotó como humo.",
              failText: "La nube de esporas te cayó en la cara y te dejó mareada.",
              okReward: 0.2,
              failReward: -0.3,
            },
          },
        },
        {
          id: "buho",
          label: "búho",
          kind: "persona",
          desc: "Un búho grande y gris en una rama baja, con los ojos amarillos fijos en ti sin parpadear.",
          reactions: {
            jugar: {
              p: 0.4,
              okText: "Giró la cabeza y tú giraste la tuya. Otra vez. El búho estaba jugando, seguro.",
              failText: "Abrió las alas de golpe, enorme, y chilló. Casi te mueres del susto.",
              okReward: 0.5,
              failReward: -0.5,
            },
            oler: {
              p: 0.7,
              okText: "Huele a plumas secas y a ratón. Te miró como diciendo 'ya está bien'.",
              failText: "Te acercaste demasiado: bajó en picada sobre tu cabeza y te rozó con las garras.",
              okReward: 0.2,
              failReward: -0.4,
            },
            tocar: {
              p: 0.2,
              okText: "Te dejó tocarle el pecho: las plumas son más suaves que cualquier cosa que conozcas.",
              failText: "Te picoteó la pata con ese pico curvo. Sangró un poquito.",
              okReward: 0.6,
              failReward: -0.6,
              effects: { energy: -0.3 },
            },
            esconderse: {
              p: 0.8,
              okText: "Te agachaste bajo un helecho y el búho te perdió de vista. Ganaste.",
              failText: "Los búhos ven en la oscuridad: te encontró al instante, sin moverse.",
              okReward: 0.3,
              failReward: -0.1,
            },
          },
        },
        {
          id: "zarzas",
          label: "zarzas",
          kind: "cosa",
          desc: "Un matorral de zarzas espinosas, con moras negras gordas colgando bien adentro.",
          reactions: {
            comer: {
              p: 0.45,
              okText: "Alcanzaste una mora sin pincharte: dulce, jugosa, morada. La mejor cosa del bosque.",
              failText: "Metiste el hocico y las espinas te dejaron la nariz llena de rasguños.",
              okReward: 0.6,
              failReward: -0.5,
            },
            tocar: {
              p: 0.3,
              okText: "Tocaste una rama por el lado sin espinas. Es dura y verde.",
              failText: "Espina directo en la pata. Ardió como fuego.",
              okReward: 0.1,
              failReward: -0.5,
              effects: { energy: -0.15 },
            },
            esconderse: {
              p: 0.35,
              okText: "Encontraste un túnel entre las zarzas: un escondite perfecto que nadie más cabe.",
              failText: "Te enredaste en las espinas y salir te costó pelos y un buen rato.",
              okReward: 0.4,
              failReward: -0.6,
              effects: { energy: -0.3 },
            },
            oler: {
              p: 0.9,
              okText: "Huele a mora madura y a hojas verdes. Se te hizo agua la boca.",
              failText: "Una avispa salió de entre las moras y te persiguió un rato.",
              okReward: 0.2,
              failReward: -0.2,
            },
          },
        },
        {
          id: "arbol-alto",
          label: "árbol alto",
          kind: "cosa",
          desc: "El árbol más alto de la espesura, con corteza rugosa y ramas que se pierden en la niebla.",
          reactions: {
            trepar: {
              p: 0.35,
              okText: "Trepaste hasta una rama alta: se ve el claro, el arroyo y una montaña azul a lo lejos.",
              failText: "A medio camino la corteza se soltó y caíste de espaldas sobre las raíces.",
              okReward: 0.7,
              failReward: -0.7,
              effects: { energy: -0.3 },
              requiresEnergy: 0.3,
            },
            tocar: {
              p: 0.95,
              okText: "La corteza es áspera y tibia. Adentro se oye algo que cruje, como si respirara.",
              failText: "Te clavaste una astilla en la almohadilla de la pata.",
              okReward: 0.2,
              failReward: -0.15,
            },
            oler: {
              p: 0.9,
              okText: "Huele a resina y a lluvia guardada. Un olor de cosa antigua.",
              failText: "Había un nido de hormigas rojas en la base. Te picaron.",
              okReward: 0.15,
              failReward: -0.2,
            },
            esconderse: {
              p: 0.75,
              okText: "Entre dos raíces enormes hay un hueco justo de tu tamaño. Ahí nadie te ve.",
              failText: "El hueco entre las raíces tenía barro hasta el fondo y te hundiste.",
              okReward: 0.3,
              failReward: -0.2,
            },
          },
        },
      ],
    },
    {
      id: "cueva",
      name: "la cueva",
      desc: "Una cueva baja y fresca al final de la espesura; el eco devuelve cada pasito y huele a piedra mojada.",
      danger: 0.5,
      links: ["espesura"],
      objects: [
        {
          id: "eco",
          label: "eco",
          kind: "idea",
          desc: "Cada sonido que haces vuelve desde el fondo, un poco más tarde y un poco más bajo.",
          reactions: {
            jugar: {
              p: 0.9,
              okText: "Gritaste '¡hola!' y la cueva te respondió 'hola… ola… la'. Te reíste y ella se rió.",
              failText: "Gritaste tan fuerte que el eco volvió como un trueno y te asustaste de ti misma.",
              okReward: 0.4,
              failReward: -0.15,
              effects: { boredom: -0.3 },
            },
            oler: {
              p: 0.95,
              okText: "El eco no huele. Pero la cueva huele a mineral y a agua vieja.",
              failText: "Respiraste polvo de la cueva y estornudaste; el eco estornudó contigo.",
              okReward: 0.1,
              failReward: -0.05,
            },
            tocar: {
              p: 0.5,
              okText: "Pusiste la pata en la pared y sentiste el eco como una vibración. Raro y lindo.",
              failText: "La pared estaba resbalosa de humedad y te fuiste de costado.",
              okReward: 0.2,
              failReward: -0.1,
            },
          },
        },
        {
          id: "murcielagos",
          label: "murciélagos",
          kind: "cosa",
          desc: "Un racimo de murciélagos colgando del techo, moviéndose apenas, chillando bajito.",
          hiddenAfter: 2,
          reactions: {
            oler: {
              p: 0.8,
              okText: "Huele fuerte, a amoniaco y a cuero viejo. Fascinante y asqueroso.",
              failText: "Algo tibio te cayó en la cabeza desde el techo. Mejor no preguntar qué.",
              okReward: 0.2,
              failReward: -0.3,
            },
            jugar: {
              p: 0.2,
              okText: "Chillaste bajito y uno te respondió. Conversaron un rato.",
              failText: "Todos salieron volando a la vez, un remolino de alas chocándote la cara.",
              okReward: 0.4,
              failReward: -0.6,
              effects: { energy: -0.3 },
            },
            esconderse: {
              p: 0.85,
              okText: "Te quedaste quieta en la sombra y los murciélagos ni te notaron.",
              failText: "Pisaste una piedra suelta y el ruido despertó a la mitad de la colonia.",
              okReward: 0.25,
              failReward: -0.3,
            },
          },
        },
        {
          id: "cristal-que-brilla",
          label: "cristal que brilla",
          kind: "cosa",
          desc: "En el fondo de la cueva, una veta de cristal morado que brilla sola, sin luz de afuera.",
          hiddenAfter: 3,
          reactions: {
            tocar: {
              p: 0.9,
              okText: "Está tibio, no frío como la piedra, y brilla más fuerte cuando lo tocas.",
              failText: "Tenía un filo escondido y te cortó la almohadilla.",
              okReward: 0.6,
              failReward: -0.3,
            },
            comer: {
              p: 0.05,
              okText: "Lamiste el cristal: sabe a chispa. Se te erizó todo el pelo.",
              failText: "Mordiste el cristal y casi te rompes un diente. Un dolor eléctrico hasta la cola.",
              okReward: 0.3,
              failReward: -0.7,
              effects: { energy: -0.3 },
            },
            oler: {
              p: 0.9,
              okText: "Huele a tormenta, a ese olor del aire antes de que caiga un rayo.",
              failText: "El brillo te encandiló y te quedaste viendo manchas moradas un rato.",
              okReward: 0.3,
              failReward: -0.1,
            },
            jugar: {
              p: 0.7,
              okText: "Moviste la cabeza y el brillo morado bailó en las paredes de la cueva.",
              failText: "Tanto mirar el cristal te dejó mareada y con dolor de cabeza.",
              okReward: 0.35,
              failReward: -0.2,
              effects: { boredom: -0.2 },
            },
          },
        },
        {
          id: "charco-oscuro",
          label: "charco oscuro",
          kind: "cosa",
          desc: "Un charco negro y quieto en el suelo de la cueva; no se ve qué tan hondo es.",
          hiddenAfter: 2,
          reactions: {
            tocar: {
              p: 0.6,
              okText: "El agua está helada y quieta; tu pata desaparece en lo negro y vuelve limpia.",
              failText: "Era mucho más hondo de lo que parecía: caíste entera y saliste temblando.",
              okReward: 0.3,
              failReward: -0.5,
              effects: { energy: -0.2 },
            },
            oler: {
              p: 0.9,
              okText: "Huele a azufre, apenas, y a piedra que nunca ha visto el sol.",
              failText: "Un gas salió del charco en burbujas y te dejó tosiendo.",
              okReward: 0.2,
              failReward: -0.2,
            },
            comer: {
              p: 0.2,
              okText: "Bebiste un sorbito. Sabe a fierro. No pasó nada, pero no lo repitas.",
              failText: "El agua negra te dio un dolor de panza y escalofríos toda la noche.",
              okReward: 0.05,
              failReward: -0.6,
              effects: { energy: -0.3 },
            },
          },
        },
      ],
    },
  ],
};

// --- 🏙️ la ciudad ---

const CIUDAD: ImaginedEnvSpec = {
  id: "ciudad",
  name: "La ciudad",
  emoji: "🏙️",
  intro: "Una ciudad ruidosa con plaza, mercado, un callejón y una biblioteca escondida.",
  verbs: [
    { id: "mirar", label: "mirar", riskHint: 0.05, costEnergy: 0.03 },
    { id: "hablar", label: "hablar con", riskHint: 0.2, costEnergy: 0.06 },
    { id: "comer", label: "comer", riskHint: 0.5, costEnergy: 0.08 },
    { id: "cruzar", label: "cruzar", riskHint: 0.6, costEnergy: 0.1 },
    { id: "seguir", label: "seguir a", riskHint: 0.4, costEnergy: 0.12 },
    { id: "esconderse", label: "esconderse en", riskHint: 0.1, costEnergy: 0.05, ludic: true },
  ],
  ambient: {
    day: [
      "Es de día: bocinas, un vendedor gritando 'ricas mandarinas' y sol pegando en el cemento.",
      "Mediodía en la ciudad: huele a pollo a la brasa y las veredas están llenas de gente apurada.",
      "El cielo está gris de siempre, una garúa fina moja todo y las combis pasan a toda velocidad.",
    ],
    night: [
      "Es de noche: luces naranjas en los postes, música lejana y un perro que ladra a lo lejos.",
      "La ciudad de noche huele a anticucho y a humo; la gente camina más rápido y habla más bajo.",
      "Está oscuro y frío; los faros de los carros barren las paredes y las sombras se mueven.",
    ],
  },
  zones: [
    {
      id: "plaza",
      name: "la plaza",
      desc: "Una plaza con pileta, bancas verdes, palomas por todos lados y una avenida ruidosa en un costado.",
      danger: 0.1,
      links: ["mercado", "callejon"],
      objects: [
        {
          id: "paloma",
          label: "paloma",
          kind: "cosa",
          desc: "Una paloma gorda y gris que camina moviendo la cabeza y picotea migas del piso.",
          reactions: {
            mirar: {
              p: 0.95,
              okText: "Tiene el cuello verde y morado cuando le da el sol. No se le nota de lejos.",
              failText: "Te quedaste mirándola tanto que otra paloma te pasó volando encima y te ensució.",
              okReward: 0.2,
              failReward: -0.15,
            },
            seguir: {
              p: 0.6,
              okText: "La seguiste a saltitos hasta la pileta y ahí se bañó, salpicando. Rico.",
              failText: "Voló a la cornisa apenas diste tres pasos. Perdiste.",
              okReward: 0.3,
              failReward: -0.1,
            },
            hablar: {
              p: 0.3,
              okText: "Le dijiste 'hola' y respondió 'currucucú' inclinando la cabeza. Una conversación.",
              failText: "Te ignoró completamente y siguió picoteando una miga.",
              okReward: 0.3,
              failReward: -0.1,
            },
            comer: {
              p: 0.05,
              okText: "Le quitaste una miga del pico. Sabía a pan viejo. Ella te miró feo.",
              failText: "Le saltaste encima y se fue volando; te caíste en el charco de la pileta.",
              okReward: 0.05,
              failReward: -0.3,
            },
          },
        },
        {
          id: "semaforo",
          label: "semáforo",
          kind: "cosa",
          desc: "Un semáforo en la esquina de la avenida: cambia de rojo a verde y los carros arrancan con todo.",
          reactions: {
            mirar: {
              p: 0.95,
              okText: "Rojo, luego verde, luego ámbar, luego rojo. Los carros se paran cuando está en rojo.",
              failText: "Te distrajiste con las luces y un ciclista casi te lleva de encuentro.",
              okReward: 0.3,
              failReward: -0.2,
            },
            cruzar: {
              p: 0.8,
              okText: "Esperaste al rojo y cruzaste tranquila hasta la otra vereda. Todos se detuvieron.",
              failText: "Cruzaste con la luz en verde: un carro pasó rozándote, bocineando, y te tiró al piso.",
              okReward: 0.4,
              failReward: -0.8,
              effects: { energy: -0.3 },
            },
            esconderse: {
              p: 0.7,
              okText: "Te pegaste detrás del poste del semáforo: nadie te vio pasar.",
              failText: "El poste es demasiado delgado para esconderte. Todo el mundo te vio.",
              okReward: 0.15,
              failReward: -0.05,
            },
          },
        },
        {
          id: "combi",
          label: "combi",
          kind: "cosa",
          desc: "Una combi blanca con rayas de colores, música a todo volumen y un cobrador gritando '¡sube, sube!'.",
          reactions: {
            mirar: {
              p: 0.9,
              okText: "Va llenísima, la gente apretada contra las ventanas, y para en cualquier sitio.",
              failText: "Frenó de golpe delante de ti y el humo negro del tubo te hizo toser.",
              okReward: 0.2,
              failReward: -0.15,
            },
            seguir: {
              p: 0.2,
              okText: "Corriste detrás dos cuadras y se detuvo: viste cómo bajan y suben en dos segundos.",
              failText: "Arrancó a toda velocidad y casi te atropella al doblar la esquina.",
              okReward: 0.4,
              failReward: -0.7,
              effects: { energy: -0.3 },
            },
            hablar: {
              p: 0.5,
              okText: "El cobrador te gritó '¡habla, causa!' y se rió. Te sentiste parte de algo.",
              failText: "El cobrador ni te miró: gritaba 'todo Javier Prado' a otra gente.",
              okReward: 0.25,
              failReward: -0.1,
            },
            esconderse: {
              p: 0.4,
              okText: "Te subiste sin que nadie te viera y viajaste tres cuadras entre piernas. Aventura.",
              failText: "El cobrador te vio al toque y te bajó por la ventana.",
              okReward: 0.4,
              failReward: -0.3,
            },
          },
        },
        {
          id: "heladero",
          label: "heladero",
          kind: "persona",
          desc: "Un heladero con carrito amarillo y una corneta que suena 'tururú' cada vez que pasa alguien.",
          reactions: {
            hablar: {
              p: 0.75,
              okText: "Te contó que el de lúcuma es el que más vende y te regaló una galletita de barquillo.",
              failText: "Estaba ocupado con una fila de niños y te dijo 'ahorita, ahorita' y nunca volvió.",
              okReward: 0.4,
              failReward: -0.1,
            },
            comer: {
              p: 0.5,
              okText: "Se cayó una bola de helado de chocolate al piso y la lamiste. Frío y dulce y perfecto.",
              failText: "Comiste helado tan rápido que te dio un dolor de cabeza congelante.",
              okReward: 0.5,
              failReward: -0.3,
              effects: { energy: 0.1 },
            },
            seguir: {
              p: 0.8,
              okText: "Seguiste el 'tururú' por toda la plaza: para donde hay niños y se queda un rato.",
              failText: "Empujó el carrito muy rápido y lo perdiste entre la gente.",
              okReward: 0.25,
              failReward: -0.1,
            },
            mirar: {
              p: 0.95,
              okText: "Abre la tapa, sale vapor frío, sirve con una cuchara redonda. Cada vez igual.",
              failText: "Miraste tanto que te confundió con un cliente y se molestó cuando no compraste.",
              okReward: 0.15,
              failReward: -0.05,
            },
          },
        },
      ],
    },
    {
      id: "mercado",
      name: "el mercado",
      desc: "Un mercado techado, apretado y ruidoso: puestos de fruta, olor a anticuchos y gente gritando precios.",
      danger: 0.3,
      links: ["plaza", "callejon", "biblioteca"],
      objects: [
        {
          id: "vendedora-de-anticuchos",
          label: "vendedora de anticuchos",
          kind: "persona",
          desc: "Una señora con mandil abanicando la parrilla; los anticuchos chisporrotean y el humo huele a gloria.",
          reactions: {
            hablar: {
              p: 0.7,
              okText: "Te dijo 'hola, mi amor' y te contó que el secreto es el ají panca y la paciencia.",
              failText: "Tenía una cola enorme y te espantó con el abanico: 'ahorita no, ahorita no'.",
              okReward: 0.5,
              failReward: -0.15,
              effects: { loneliness: -0.2 },
            },
            comer: {
              p: 0.55,
              okText: "Te regaló un pedacito de anticucho: ahumado, jugoso, con ají. Lo mejor de la ciudad.",
              failText: "Agarraste uno de la parrilla sin permiso y te quemaste la lengua feo.",
              okReward: 0.6,
              failReward: -0.5,
              effects: { energy: 0.15 },
            },
            mirar: {
              p: 0.95,
              okText: "Da vuelta los palitos justo cuando el borde se pone negro. Nunca antes.",
              failText: "El humo de la parrilla te entró a los ojos y no viste nada un buen rato.",
              okReward: 0.2,
              failReward: -0.1,
            },
            seguir: {
              p: 0.6,
              okText: "La seguiste a la trastienda: guarda la carne en un balde con hielo y ají.",
              failText: "Te pisó sin querer con sus zapatos de suela gruesa. No te vio.",
              okReward: 0.3,
              failReward: -0.4,
            },
          },
        },
        {
          id: "fruta-caida",
          label: "fruta caída",
          kind: "cosa",
          desc: "Un mango maduro que cayó del puesto y rodó bajo la mesa, con un lado golpeado.",
          reactions: {
            comer: {
              p: 0.7,
              okText: "Dulcísimo, chorreante, con fibras que se quedan en los dientes. Mango.",
              failText: "El lado golpeado estaba podrido y sabía a alcohol. Te dio arcadas.",
              okReward: 0.5,
              failReward: -0.4,
              effects: { energy: 0.1 },
            },
            mirar: {
              p: 0.95,
              okText: "Es naranja con manchas rojas y tiene un moscardón dando vueltas encima.",
              failText: "Te agachaste a mirar y te golpeaste la cabeza con el borde de la mesa.",
              okReward: 0.15,
              failReward: -0.15,
            },
            esconderse: {
              p: 0.85,
              okText: "Debajo de la mesa, junto al mango, es fresco y oscuro. Buen escondite.",
              failText: "El vendedor barrió debajo de la mesa y te sacó con la escoba.",
              okReward: 0.25,
              failReward: -0.2,
            },
          },
        },
        {
          id: "gato-del-mercado",
          label: "gato del mercado",
          kind: "persona",
          desc: "Un gato atigrado, gordo y serio, echado sobre unos sacos de papa como si fuera el dueño.",
          reactions: {
            hablar: {
              p: 0.4,
              okText: "Abrió un ojo, dijo 'mrrp' y volvió a cerrarlo. Para un gato, eso es amistad.",
              failText: "Te bufó con las orejas pegadas y te tiró un zarpazo al aire.",
              okReward: 0.4,
              failReward: -0.3,
            },
            seguir: {
              p: 0.5,
              okText: "Te llevó por atrás de los puestos hasta un rincón lleno de cabezas de pescado.",
              failText: "Se subió de un salto a un techo al que tú no llegas y te miró desde arriba.",
              okReward: 0.3,
              failReward: -0.15,
            },
            mirar: {
              p: 0.9,
              okText: "Tiene una oreja rota y la cola muy larga. Mira a todos como si les cobrara.",
              failText: "Te miró fijo hasta que tuviste que bajar la vista. Ganó él.",
              okReward: 0.2,
              failReward: -0.05,
            },
            esconderse: {
              p: 0.3,
              okText: "Te acomodaste entre los sacos junto al gato y él te dejó. Tibieza compartida.",
              failText: "Los sacos eran su territorio: te sacó a manotazos.",
              okReward: 0.4,
              failReward: -0.3,
            },
          },
        },
        {
          id: "caja-de-carton",
          label: "caja de cartón",
          kind: "cosa",
          desc: "Una caja de cartón vacía con letras rojas, tirada de lado junto al puesto de verduras.",
          reactions: {
            esconderse: {
              p: 0.9,
              okText: "Te metiste de un salto. Huele a cebolla y nadie te ve. La mejor caja del mundo.",
              failText: "La caja estaba mojada por abajo y se deshizo apenas entraste.",
              okReward: 0.4,
              failReward: -0.15,
              effects: { boredom: -0.2 },
            },
            mirar: {
              p: 0.95,
              okText: "Dice 'FRÁGIL' en rojo y tiene dibujada una copa rota.",
              failText: "Alguien la pateó mientras la mirabas y te cayó encima.",
              okReward: 0.1,
              failReward: -0.1,
            },
            comer: {
              p: 0.3,
              okText: "Mordiste una esquina. Sabe a papel y a cebolla. No es comida, pero se deja.",
              failText: "Te tragaste un pedazo y te quedó atorado. Tosiste hasta sacarlo.",
              okReward: 0.05,
              failReward: -0.3,
            },
          },
        },
      ],
    },
    {
      id: "callejon",
      name: "el callejón",
      desc: "Un callejón estrecho y oscuro detrás del mercado, con paredes grafiteadas, basura y goteras.",
      danger: 0.7,
      links: ["plaza", "mercado"],
      objects: [
        {
          id: "perro-callejero",
          label: "perro callejero",
          kind: "persona",
          desc: "Un perro flaco y sucio con una oreja caída, gruñendo bajito junto a un tacho de basura.",
          reactions: {
            hablar: {
              p: 0.35,
              okText: "Dejó de gruñir cuando le hablaste bajito, y hasta movió la cola una vez.",
              failText: "Te enseñó los dientes y ladró tan fuerte que retrocediste hasta la pared.",
              okReward: 0.5,
              failReward: -0.4,
            },
            seguir: {
              p: 0.2,
              okText: "Te llevó a un rincón donde guarda huesos y te dejó oler uno. Confianza.",
              failText: "Se dio vuelta de golpe y te mordió la pata. Escapaste cojeando.",
              okReward: 0.5,
              failReward: -0.8,
              effects: { energy: -0.3 },
            },
            esconderse: {
              p: 0.6,
              okText: "Te metiste detrás del tacho antes de que te olfateara. Pasó de largo.",
              failText: "Te olió al toque y te sacó del escondite a ladridos.",
              okReward: 0.3,
              failReward: -0.4,
            },
            mirar: {
              p: 0.85,
              okText: "Tiene las costillas marcadas y una cicatriz en el hocico. Cuida su basura.",
              failText: "Lo miraste a los ojos y lo tomó como un desafío: se te vino encima.",
              okReward: 0.2,
              failReward: -0.4,
            },
          },
        },
        {
          id: "charco-con-aceite",
          label: "charco con aceite",
          kind: "cosa",
          desc: "Un charco con una mancha de aceite encima que hace arcoíris cuando le da la luz.",
          reactions: {
            mirar: {
              p: 0.95,
              okText: "El aceite hace colores: morado, verde, dorado, moviéndose. Feo y lindo a la vez.",
              failText: "Un carro pasó por el charco y te bañó de agua sucia.",
              okReward: 0.3,
              failReward: -0.3,
            },
            comer: {
              p: 0.1,
              okText: "Lamiste el borde. Sabía a fierro y a gasolina. No pasó nada. Pura suerte.",
              failText: "El agua con aceite te dio un dolor de panza horrible: vomitaste dos veces.",
              okReward: -0.1,
              failReward: -0.7,
              effects: { energy: -0.3 },
            },
            cruzar: {
              p: 0.5,
              okText: "Saltaste el charco de un brinco largo y caíste seca del otro lado.",
              failText: "Resbalaste en el aceite y caíste de panza en el agua negra.",
              okReward: 0.3,
              failReward: -0.4,
            },
          },
        },
        {
          id: "grafiti",
          label: "grafiti",
          kind: "cosa",
          desc: "Un grafiti enorme de un jaguar azul con los ojos amarillos que parece mirarte desde la pared.",
          reactions: {
            mirar: {
              p: 0.95,
              okText: "El jaguar tiene manchas negras y dice 'LIMA' abajo en letras gordas. Alguien lo pintó de noche.",
              failText: "Estaba tan oscuro que solo viste los ojos amarillos y te asustaste.",
              okReward: 0.3,
              failReward: -0.15,
            },
            hablar: {
              p: 0.1,
              okText: "Le dijiste 'hola, jaguar' y justo un eco del callejón respondió. Casi te lo crees.",
              failText: "Le hablaste a la pared. La pared no habla. Te sentiste tonta.",
              okReward: 0.2,
              failReward: -0.1,
            },
            esconderse: {
              p: 0.8,
              okText: "Te pegaste a la pared bajo el jaguar: con tanto color, nadie te distingue.",
              failText: "La pintura estaba fresca y te quedaste azul de un lado.",
              okReward: 0.25,
              failReward: -0.2,
            },
          },
        },
        {
          id: "tacho-volcado",
          label: "tacho volcado",
          kind: "cosa",
          desc: "Un tacho de basura volcado, con bolsas rotas y un olor agrio que se siente desde lejos.",
          reactions: {
            comer: {
              p: 0.3,
              okText: "Encontraste medio pan con pollo, todavía bueno. Comida de verdad.",
              failText: "Comiste algo que llevaba días ahí: dolor de panza y escalofríos toda la tarde.",
              okReward: 0.4,
              failReward: -0.6,
              effects: { energy: -0.3 },
            },
            esconderse: {
              p: 0.75,
              okText: "Dentro del tacho vacío hay eco y oscuridad. Huele mal, pero nadie te busca ahí.",
              failText: "El tacho rodó contigo adentro cuando entraste y terminaste mareada en la pista.",
              okReward: 0.2,
              failReward: -0.3,
            },
            mirar: {
              p: 0.9,
              okText: "Hay cáscaras de plátano, una lata de Inca Kola y una rata que te miró y se fue.",
              failText: "Metiste la cabeza en una bolsa y no la podías sacar. Pánico por un minuto.",
              okReward: 0.15,
              failReward: -0.25,
            },
          },
        },
      ],
    },
    {
      id: "biblioteca",
      name: "la biblioteca",
      desc: "Una biblioteca vieja detrás del mercado, silenciosa, con estantes hasta el techo y lámparas verdes.",
      danger: 0.05,
      links: ["mercado"],
      objects: [
        {
          id: "libro-abierto",
          label: "libro abierto",
          kind: "cosa",
          desc: "Un libro gordo abierto sobre una mesa, con un dibujo de una ballena y letras apretadas.",
          reactions: {
            mirar: {
              p: 0.95,
              okText: "La ballena es azul y más grande que una combi, dice el libro. Hay muchos números al lado.",
              failText: "Las letras se movían de tanto mirarlas y te dio dolor de cabeza.",
              okReward: 0.4,
              failReward: -0.1,
            },
            comer: {
              p: 0.2,
              okText: "Mordiste una esquina de página. Sabe a polvo viejo. Nadie te vio.",
              failText: "La bibliotecaria te vio mordiendo el libro y te sacó de la oreja.",
              okReward: 0.05,
              failReward: -0.5,
            },
            esconderse: {
              p: 0.7,
              okText: "Te tapaste con la página de la ballena y te quedaste quieta. Perfecto.",
              failText: "El libro se cerró encima de ti con un golpe y levantó una nube de polvo.",
              okReward: 0.2,
              failReward: -0.2,
            },
          },
        },
        {
          id: "bibliotecaria",
          label: "bibliotecaria",
          kind: "persona",
          desc: "Una señora de lentes gruesos y chompa gris que hace 'shhh' sin levantar la vista de sus fichas.",
          hiddenAfter: 2,
          reactions: {
            hablar: {
              p: 0.6,
              okText: "Te explicó en voz baja que los libros se ordenan por letras y que el de mapas está arriba.",
              failText: "'Shhh. Aquí no se habla.' Y volvió a sus fichas.",
              okReward: 0.5,
              failReward: -0.2,
              effects: { loneliness: -0.15 },
            },
            seguir: {
              p: 0.7,
              okText: "La seguiste entre los estantes: guarda cada libro en su sitio exacto, sin mirar.",
              failText: "Te vio siguiéndola y te señaló la puerta sin decir palabra.",
              okReward: 0.35,
              failReward: -0.3,
            },
            mirar: {
              p: 0.95,
              okText: "Lee con el dedo, pasa la página, anota algo en una ficha. Siempre en ese orden.",
              failText: "Te vio mirándola y te miró de vuelta por encima de los lentes hasta que te fuiste.",
              okReward: 0.2,
              failReward: -0.1,
            },
          },
        },
        {
          id: "escalera-de-caracol",
          label: "escalera de caracol",
          kind: "lugar",
          desc: "Una escalera de fierro en espiral que sube al piso de arriba, donde está oscuro y hay más libros.",
          hiddenAfter: 3,
          reactions: {
            cruzar: {
              p: 0.55,
              okText: "Subiste dando vueltas hasta arriba: un piso entero de mapas y polvo dorado.",
              failText: "Los escalones son de rejilla y se te trabó una pata; caíste media vuelta.",
              okReward: 0.6,
              failReward: -0.5,
              effects: { energy: -0.15 },
              requiresEnergy: 0.25,
            },
            mirar: {
              p: 0.95,
              okText: "Sube girando, girando, y se pierde en la oscuridad. Tiene barandas frías.",
              failText: "Miraste hacia arriba tanto rato que te mareaste.",
              okReward: 0.2,
              failReward: -0.1,
            },
            esconderse: {
              p: 0.8,
              okText: "Debajo de la escalera hay un triángulo de sombra donde cabes perfecta.",
              failText: "Alguien bajó la escalera y el fierro retumbó justo sobre tu cabeza.",
              okReward: 0.25,
              failReward: -0.2,
            },
          },
        },
        {
          id: "lampara-verde",
          label: "lámpara verde",
          kind: "cosa",
          desc: "Una lámpara de mesa con pantalla de vidrio verde que hace un círculo de luz tibia sobre la madera.",
          hiddenAfter: 2,
          reactions: {
            mirar: {
              p: 0.95,
              okText: "La luz verde hace que todo alrededor parezca más callado. Da sueño bonito.",
              failText: "Miraste el foco directo y te quedaron manchas verdes en los ojos.",
              okReward: 0.3,
              failReward: -0.15,
            },
            esconderse: {
              p: 0.5,
              okText: "Te acurrucaste en el círculo de luz tibia sobre la mesa y casi te duermes.",
              failText: "La bibliotecaria te encontró sobre la mesa y te bajó con un 'no, señorita'.",
              okReward: 0.4,
              failReward: -0.2,
              effects: { energy: 0.15 },
            },
            comer: {
              p: 0.1,
              okText: "Lamiste el vidrio verde. Tibio, sin sabor. Raro.",
              failText: "El foco estaba ardiendo y te quemaste la lengua.",
              okReward: 0.0,
              failReward: -0.6,
              effects: { energy: -0.3 },
            },
          },
        },
      ],
    },
  ],
};

// --- 🎬 el cine ---

const CINE: ImaginedEnvSpec = {
  id: "cine",
  name: "El cine",
  emoji: "🎬",
  intro: "Un cine de barrio con lobby de alfombra roja, una sala oscura y una azotea con vista.",
  verbs: [
    { id: "mirar", label: "mirar", riskHint: 0.05, costEnergy: 0.03 },
    { id: "escuchar", label: "escuchar", riskHint: 0.05, costEnergy: 0.03 },
    { id: "comer", label: "comer", riskHint: 0.4, costEnergy: 0.08 },
    { id: "sentarse", label: "sentarse en", riskHint: 0.1, costEnergy: 0.02 },
    { id: "hablar", label: "hablar con", riskHint: 0.3, costEnergy: 0.06 },
    { id: "colarse", label: "colarse en", riskHint: 0.7, costEnergy: 0.12, ludic: true },
  ],
  ambient: {
    day: [
      "Es de día: entra luz por la puerta de vidrio y el cine está casi vacío, con olor a canchita recién hecha.",
      "Función de la tarde: hay niños corriendo por el lobby y una señora limpiando la alfombra.",
      "Afuera hay sol y adentro penumbra; se oye el zumbido de la máquina de canchita.",
    ],
    night: [
      "Es de noche: el letrero de afuera parpadea en rojo y la fila para la última función da la vuelta.",
      "Función de noche: parejas con mantas, olor a mantequilla y risas apagadas que salen de la sala.",
      "Está oscuro y el cine está en silencio; solo se oye el proyector ronroneando arriba.",
    ],
  },
  zones: [
    {
      id: "lobby",
      name: "el lobby",
      desc: "Un lobby de alfombra roja gastada, afiches en las paredes, una boletería y la máquina de canchita.",
      danger: 0.1,
      links: ["sala", "azotea"],
      objects: [
        {
          id: "canchita",
          label: "canchita",
          kind: "cosa",
          desc: "Una montaña de canchita amarilla saltando dentro de la máquina, con mantequilla derretida encima.",
          reactions: {
            comer: {
              p: 0.9,
              okText: "Crujiente, salada, con mantequilla. Comiste hasta que se te llenó la panza.",
              failText: "Comiste demasiado rápido y un grano sin reventar te dolió en la muela.",
              okReward: 0.5,
              failReward: -0.2,
              effects: { energy: 0.2 },
            },
            mirar: {
              p: 0.95,
              okText: "Los granos saltan de golpe, uno por uno, y se abren como florcitas blancas.",
              failText: "Un grano saltó fuera de la máquina y te pegó en el ojo.",
              okReward: 0.2,
              failReward: -0.1,
            },
            escuchar: {
              p: 0.95,
              okText: "Pop. Pop. Pop-pop-pop. Luego muchos a la vez, como lluvia en techo de calamina.",
              failText: "Se acabó justo cuando empezaste a escuchar. Silencio y olor a quemado.",
              okReward: 0.2,
              failReward: -0.05,
            },
          },
        },
        {
          id: "acomodador",
          label: "acomodador",
          kind: "persona",
          desc: "Un joven de chaleco rojo y linterna en la mano que revisa entradas en la puerta de la sala.",
          reactions: {
            hablar: {
              p: 0.65,
              okText: "Te dijo que la película de robots es la mejor y que la de terror es para valientes.",
              failText: "Te pidió tu entrada. No tienes entrada. Te señaló la boletería.",
              okReward: 0.4,
              failReward: -0.15,
              effects: { loneliness: -0.15 },
            },
            colarse: {
              p: 0.2,
              okText: "Pasaste agachada entre dos personas mientras revisaba otra entrada. Adentro.",
              failText: "Te alumbró con la linterna en plena cara y te sacó del brazo hasta la puerta.",
              okReward: 0.5,
              failReward: -0.6,
              effects: { energy: -0.2 },
            },
            mirar: {
              p: 0.95,
              okText: "Rompe la entrada en dos, se queda una mitad y devuelve la otra. Siempre igual.",
              failText: "Te vio mirándolo fijo y te preguntó si estabas perdida.",
              okReward: 0.15,
              failReward: -0.05,
            },
          },
        },
        {
          id: "afiche-de-robots",
          label: "afiche de robots",
          kind: "cosa",
          desc: "Un afiche gigante de una película de robots: un robot plateado con ojos azules bajo una lluvia de chispas.",
          reactions: {
            mirar: {
              p: 0.95,
              okText: "El robot tiene un brazo roto y detrás hay una ciudad ardiendo. Dice 'ESTRENO'.",
              failText: "Estaba tan alto que te torciste el cuello mirándolo.",
              okReward: 0.3,
              failReward: -0.1,
            },
            hablar: {
              p: 0.05,
              okText: "Le dijiste 'hola, robot' y una luz del afiche parpadeó. Casi seguro fue casualidad.",
              failText: "Le hablaste al papel. El papel no contesta. Un niño se rió de ti.",
              okReward: 0.15,
              failReward: -0.15,
            },
            sentarse: {
              p: 0.9,
              okText: "Te sentaste debajo del afiche a mirar a la gente entrar. Buen sitio para observar.",
              failText: "El afiche se despegó de la pared y te cayó encima como una sábana.",
              okReward: 0.2,
              failReward: -0.15,
            },
          },
        },
        {
          id: "maquina-de-gaseosa",
          label: "máquina de gaseosa",
          kind: "cosa",
          desc: "Una máquina que zumba y tiene botones de colores: Inca Kola, Coca Cola, agua. Al pie hay una bandeja pegajosa.",
          reactions: {
            comer: {
              p: 0.5,
              okText: "Lamiste la gaseosa amarilla que chorreó en la bandeja. Dulce como chicle. Burbujas en la nariz.",
              failText: "Tomaste tanto que te dio hipo y te dolió la panza de gas.",
              okReward: 0.3,
              failReward: -0.3,
            },
            escuchar: {
              p: 0.9,
              okText: "Zumba bajito todo el tiempo, y cada tanto hace 'clonk' cuando algo cae adentro.",
              failText: "Alguien la pateó justo cuando pegaste la oreja. Te retumbó la cabeza.",
              okReward: 0.15,
              failReward: -0.2,
            },
            mirar: {
              p: 0.95,
              okText: "Aprietas un botón, sale un vaso, y cae líquido de color. Magia con botones.",
              failText: "Las luces de los botones parpadearon tan rápido que te mareaste.",
              okReward: 0.2,
              failReward: -0.05,
            },
            colarse: {
              p: 0.3,
              okText: "Te metiste por la ranura de abajo y salió un vaso de gaseosa gratis. Nadie vio.",
              failText: "Te quedaste atorada en la ranura y el acomodador tuvo que sacarte.",
              okReward: 0.4,
              failReward: -0.4,
            },
          },
        },
      ],
    },
    {
      id: "sala",
      name: "la sala",
      desc: "Una sala oscura con filas de butacas rojas, una pantalla enorme y un público que susurra y come canchita.",
      danger: 0.2,
      links: ["lobby", "proyeccion"],
      objects: [
        {
          id: "pelicula-de-robots",
          label: "película de robots",
          kind: "idea",
          desc: "En la pantalla, un robot plateado busca a su creadora por una ciudad en ruinas; hay chispas, lluvia y una canción triste.",
          reactions: {
            mirar: {
              p: 0.95,
              okText: "Viste una historia de un robot que aprende a tener miedo y al final encuentra a su creadora. Lloraste un poquito.",
              failText: "Alguien alto se sentó delante y solo viste su cabeza durante toda la escena buena.",
              okReward: 0.5,
              failReward: -0.15,
              effects: { boredom: -0.4 },
            },
            escuchar: {
              p: 0.9,
              okText: "La canción del robot es lenta y con campanitas. Se te quedó pegada.",
              failText: "El sonido estaba tan fuerte en la explosión que te tapaste las orejas.",
              okReward: 0.3,
              failReward: -0.15,
            },
            hablar: {
              p: 0.3,
              okText: "Susurraste '¡corre, robot!' y una niña al lado se rió bajito contigo.",
              failText: "¡Shhh! Toda la fila se volteó a mirarte. Te hundiste en la butaca.",
              okReward: 0.2,
              failReward: -0.3,
            },
          },
        },
        {
          id: "pelicula-de-terror",
          label: "película de terror",
          kind: "idea",
          desc: "En la pantalla, una casa vieja de noche, una puerta que cruje sola y música que sube y sube.",
          reactions: {
            mirar: {
              p: 0.4,
              okText: "Aguantaste la escena entera: el monstruo era una máscara y al final se ríen. Valiente.",
              failText: "El monstruo salió de golpe con un grito y saltaste tan alto que botaste la canchita del vecino.",
              okReward: 0.6,
              failReward: -0.5,
              effects: { energy: -0.15 },
            },
            escuchar: {
              p: 0.5,
              okText: "La música sube despacito, se calla, y ahí sabes que viene el susto. Aprendiste el truco.",
              failText: "Cerraste los ojos para no ver y el sonido fue peor: gritaste tú sola.",
              okReward: 0.4,
              failReward: -0.4,
            },
            hablar: {
              p: 0.25,
              okText: "Le dijiste bajito a tu vecino 'no abras esa puerta' y él asintió, serio.",
              failText: "¡Shhh! Alguien te tiró una canchita en la cabeza por hablar.",
              okReward: 0.2,
              failReward: -0.3,
            },
            sentarse: {
              p: 0.8,
              okText: "Te hundiste en la butaca con las patas tapándote los ojos, mirando entre los dedos.",
              failText: "Te sentaste en el pasillo y el acomodador te alumbró: 'a tu sitio'.",
              okReward: 0.2,
              failReward: -0.2,
            },
          },
        },
        {
          id: "butaca-del-fondo",
          label: "butaca del fondo",
          kind: "lugar",
          desc: "Una butaca en la última fila, con el asiento roto y chicle pegado debajo, pero desde ahí se ve todo.",
          reactions: {
            sentarse: {
              p: 0.9,
              okText: "Desde el fondo ves la pantalla completa y todas las cabezas. Te sientes dueña de la sala.",
              failText: "El asiento roto se cerró contigo adentro como una almeja.",
              okReward: 0.4,
              failReward: -0.2,
              effects: { energy: 0.1 },
            },
            mirar: {
              p: 0.95,
              okText: "Tiene el número 47 en una plaquita y el terciopelo gastado en el borde.",
              failText: "Metiste la cabeza bajo el asiento a mirar y el chicle se te pegó en la oreja.",
              okReward: 0.15,
              failReward: -0.15,
            },
            comer: {
              p: 0.3,
              okText: "Encontraste canchita de otra función entre los cojines. Vieja, pero canchita.",
              failText: "Mordiste el chicle pegado por error. Duro, viejo, asqueroso.",
              okReward: 0.2,
              failReward: -0.4,
            },
          },
        },
        {
          id: "publico",
          label: "público",
          kind: "persona",
          desc: "Filas de gente en la penumbra: un señor que ronca, una pareja con manta, niños que susurran.",
          reactions: {
            hablar: {
              p: 0.3,
              okText: "Un niño te respondió en susurros y te convidó canchita. Amigos de sala.",
              failText: "¡Shhhhh! Veinte personas a la vez. Te quedaste chiquita en la butaca.",
              okReward: 0.4,
              failReward: -0.4,
            },
            escuchar: {
              p: 0.9,
              okText: "Se ríen todos juntos, respiran todos juntos, y alguien suspira en el momento triste.",
              failText: "El señor de atrás roncaba tan fuerte que no escuchaste otra cosa.",
              okReward: 0.3,
              failReward: -0.1,
            },
            mirar: {
              p: 0.9,
              okText: "Las caras se ponen azules con la pantalla y todas miran al mismo sitio, como hipnotizadas.",
              failText: "Alguien te vio mirándolo en vez de mirar la película y te hizo 'psst'.",
              okReward: 0.25,
              failReward: -0.1,
            },
            colarse: {
              p: 0.5,
              okText: "Te metiste bajo la manta de la pareja y viste el resto de la película calientita.",
              failText: "La pareja saltó del susto y la manta terminó en el pasillo, contigo enredada.",
              okReward: 0.4,
              failReward: -0.4,
            },
          },
        },
      ],
    },
    {
      id: "proyeccion",
      name: "la cabina de proyección",
      desc: "Una cabina angosta y caliente arriba de la sala, con un ventanuco por donde sale el haz de luz.",
      danger: 0.4,
      links: ["sala"],
      objects: [
        {
          id: "proyector",
          label: "proyector",
          kind: "cosa",
          desc: "Una máquina enorme y caliente que ronronea y lanza un haz de luz lleno de polvo hacia la sala.",
          reactions: {
            mirar: {
              p: 0.9,
              okText: "La película es una cinta larga que pasa delante de una luz muy fuerte: así se hace la imagen.",
              failText: "Miraste directo al haz y te quedaste ciega un buen rato, viendo un sol.",
              okReward: 0.5,
              failReward: -0.4,
            },
            escuchar: {
              p: 0.95,
              okText: "Ronronea como un gato gigante y hace 'tac-tac-tac' muy rápido, como un corazón.",
              failText: "Chirrió de golpe y el proyeccionista corrió a golpearlo. Te asustaste.",
              okReward: 0.25,
              failReward: -0.1,
            },
            colarse: {
              p: 0.15,
              okText: "Pusiste una pata delante del lente y tu sombra apareció gigante en la pantalla. ¡Todos gritaron!",
              failText: "Tocaste la lámpara caliente y te quemaste feo. Olía a pelo chamuscado.",
              okReward: 0.6,
              failReward: -0.7,
              effects: { energy: -0.3 },
            },
          },
        },
        {
          id: "rollo-de-pelicula",
          label: "rollo de película",
          kind: "cosa",
          desc: "Un rollo de cinta brillante en una lata redonda; cada cuadrito es una foto casi igual a la anterior.",
          hiddenAfter: 2,
          reactions: {
            mirar: {
              p: 0.95,
              okText: "Contra la luz, cada cuadrito muestra al robot un pelito más adelante. Muchas fotos hacen movimiento.",
              failText: "Se te desenrolló medio rollo por el piso y tuviste que enrollarlo con las patas.",
              okReward: 0.5,
              failReward: -0.2,
            },
            comer: {
              p: 0.1,
              okText: "Lamiste la cinta. Sabe a plástico y a vinagre. Nada más.",
              failText: "Mordiste la cinta, se rompió y la función de abajo se cortó. Gritos. Te escondiste.",
              okReward: -0.05,
              failReward: -0.7,
              effects: { energy: -0.2 },
            },
            sentarse: {
              p: 0.85,
              okText: "La lata redonda es un asiento perfecto, fresquito y con borde.",
              failText: "La lata rodó contigo encima hasta chocar con el proyector.",
              okReward: 0.2,
              failReward: -0.2,
            },
          },
        },
        {
          id: "proyeccionista",
          label: "proyeccionista",
          kind: "persona",
          desc: "Un señor mayor con lentes en la punta de la nariz que cambia rollos y come un sánguche sin mirar.",
          hiddenAfter: 2,
          reactions: {
            hablar: {
              p: 0.6,
              okText: "Te contó que lleva treinta años ahí y que la de robots la ha visto veinte veces y siempre llora.",
              failText: "'Shh, estoy cambiando el rollo.' Y no te miró más.",
              okReward: 0.5,
              failReward: -0.15,
              effects: { loneliness: -0.2 },
            },
            comer: {
              p: 0.4,
              okText: "Te dio la mitad de su sánguche de pollo. Con mayonesa. Un gran señor.",
              failText: "Le robaste un pedazo y se molestó: 'fuera de mi cabina'.",
              okReward: 0.5,
              failReward: -0.4,
            },
            mirar: {
              p: 0.95,
              okText: "Mira por el ventanuco, ajusta una rueda, mira otra vez. Cuida la imagen como si fuera suya.",
              failText: "Te tropezaste con sus pies mirándolo y casi tumbas el rollo.",
              okReward: 0.2,
              failReward: -0.15,
            },
          },
        },
        {
          id: "ventanuco",
          label: "ventanuco",
          kind: "lugar",
          desc: "Una ventanita cuadrada en la pared por donde sale el haz de luz y se ve toda la sala desde arriba.",
          hiddenAfter: 3,
          reactions: {
            mirar: {
              p: 0.95,
              okText: "Desde arriba la sala es un mar de cabezas azules y la pantalla se ve chiquita. Todo tiene sentido.",
              failText: "El haz de luz te dio justo en los ojos al asomarte. Manchas de colores.",
              okReward: 0.6,
              failReward: -0.3,
            },
            sentarse: {
              p: 0.7,
              okText: "Te sentaste en el borde del ventanuco con las patas colgando sobre la sala. Un mirador.",
              failText: "Resbalaste del borde y caíste sobre las butacas de abajo. Gritos y risas.",
              okReward: 0.4,
              failReward: -0.6,
              effects: { energy: -0.3 },
            },
            escuchar: {
              p: 0.9,
              okText: "Desde aquí se oye la sala entera: las risas llegan un pelito después que la imagen.",
              failText: "El ventilador del proyector zumbaba tan fuerte que no oíste nada.",
              okReward: 0.3,
              failReward: -0.05,
            },
          },
        },
      ],
    },
    {
      id: "azotea",
      name: "la azotea",
      desc: "La azotea del cine: tanques de agua, una antena, ropa colgada de alguien y toda la ciudad allá abajo.",
      danger: 0.5,
      links: ["lobby"],
      objects: [
        {
          id: "borde-de-la-azotea",
          label: "borde de la azotea",
          kind: "lugar",
          desc: "El borde sin baranda de la azotea; abajo, muy abajo, pasan los carros como juguetes.",
          reactions: {
            mirar: {
              p: 0.85,
              okText: "Se ve todo: la plaza, techos de calamina, un cerro con casitas de colores. Te dio vértigo lindo.",
              failText: "Te mareaste de mirar tan abajo y tuviste que echarte al piso un rato.",
              okReward: 0.5,
              failReward: -0.3,
            },
            sentarse: {
              p: 0.2,
              okText: "Te sentaste en el mismo borde con las patas al aire. El viento y el vacío. Nunca tan viva.",
              failText: "Una ráfaga de viento te empujó y quedaste colgando de una pata. Te salvaste por un pelo.",
              okReward: 0.7,
              failReward: -0.8,
              effects: { energy: -0.3 },
            },
            escuchar: {
              p: 0.9,
              okText: "Desde arriba la ciudad es un solo ruido largo, como el mar, con bocinas de vez en cuando.",
              failText: "Un helicóptero pasó tan bajo que te aplastó las orejas de ruido.",
              okReward: 0.3,
              failReward: -0.2,
            },
          },
        },
        {
          id: "antena",
          label: "antena",
          kind: "cosa",
          desc: "Una antena de fierro oxidado, alta y delgada, que vibra con el viento y tiene un cable colgando.",
          reactions: {
            escuchar: {
              p: 0.8,
              okText: "Zumba cuando sopla el viento, una nota larga y triste, como una flauta lejana.",
              failText: "El cable suelto chicoteó con el viento y te dio en la cara.",
              okReward: 0.3,
              failReward: -0.3,
            },
            colarse: {
              p: 0.25,
              okText: "Trepaste por la antena hasta la mitad: la ciudad entera y el viento en la cara.",
              failText: "El fierro oxidado cedió y caíste sobre el tanque de agua. Sonó como un tambor.",
              okReward: 0.6,
              failReward: -0.6,
              effects: { energy: -0.3 },
              requiresEnergy: 0.3,
            },
            mirar: {
              p: 0.95,
              okText: "Tiene pájaros posados en cada travesaño, todos mirando al mismo lado.",
              failText: "Te cayó una gota de óxido con agua en el ojo.",
              okReward: 0.15,
              failReward: -0.1,
            },
          },
        },
        {
          id: "gato-de-la-azotea",
          label: "gato de la azotea",
          kind: "persona",
          desc: "Un gato blanco y flaco echado sobre el tanque de agua tibio, mirando la ciudad como si fuera suya.",
          reactions: {
            hablar: {
              p: 0.5,
              okText: "Te dijo 'miau' bajito y te hizo un sitio en el tanque. Miraron la ciudad juntas.",
              failText: "Te bufó y se fue por la cornisa sin mirar atrás. Muy digno.",
              okReward: 0.5,
              failReward: -0.2,
              effects: { loneliness: -0.2 },
            },
            sentarse: {
              p: 0.7,
              okText: "El tanque está tibio del sol y el gato ronronea. La mejor siesta del cine.",
              failText: "El gato te empujó del tanque con la pata. Su tanque.",
              okReward: 0.4,
              failReward: -0.2,
              effects: { energy: 0.15 },
            },
            mirar: {
              p: 0.95,
              okText: "Tiene un ojo azul y uno verde y una pata sin pelo. Cierra los ojos al sol como si rezara.",
              failText: "Te miró de vuelta fijo hasta que te dio vergüenza y miraste a otro lado.",
              okReward: 0.2,
              failReward: -0.05,
            },
          },
        },
        {
          id: "cielo-de-la-azotea",
          label: "cielo de la azotea",
          kind: "lugar",
          desc: "El cielo abierto sobre el cine: de día gris panza de burro, de noche unas pocas estrellas y aviones que parpadean.",
          reactions: {
            mirar: {
              p: 0.9,
              okText: "Contaste cuatro estrellas y un avión rojo que parpadeaba. El cielo de la ciudad es tacaño pero existe.",
              failText: "Estaba tan nublado que no viste nada, solo una nube naranja de luces.",
              okReward: 0.4,
              failReward: -0.1,
              effects: { boredom: -0.2 },
            },
            escuchar: {
              p: 0.9,
              okText: "Un avión pasó ronroneando muy alto y luego silencio, y luego una bocina abajo.",
              failText: "Empezó a garuar justo en tu oreja y se acabó el silencio.",
              okReward: 0.25,
              failReward: -0.05,
            },
            sentarse: {
              p: 0.95,
              okText: "Te echaste panza arriba en el piso tibio de la azotea a mirar el cielo hasta que se hizo tarde.",
              failText: "El piso de la azotea estaba mojado y te empapaste el lomo.",
              okReward: 0.3,
              failReward: -0.15,
              effects: { energy: 0.1 },
            },
          },
        },
      ],
    },
  ],
};

/** Los tres mundos, en el orden en que aparecen en el selector. */
export const IMAGINED: ImaginedEnvSpec[] = [BOSQUE, CIUDAD, CINE];
